# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  pull_request:
    branches:
      - develop
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: mkdir deb && go build -o ./bin server.go

    - name: Test
      run: go test -v ./...
    
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: server_${{ github.sha }}
        path: bin
      
  deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: server_${{ github.sha }}
          path: bin
        
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v1
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secret.KNOWN_HOSTS }}
      - name: Deploy
        run: rsync -acvz --delete ./bin ${{ secrets.USERNAME }}@${{ secrets.HOSTNAME }}:/home/${{ secrets.USERNAME }}/bin
